project:
  type: website

# add ZAS and Leibniz logos w/ hyperlinks
margin-footer: |
  <div style="text-align: center;">
    <a href="https://www.leibniz-zas.de/en/" target="_blank" rel="noopener noreferrer" style="display: inline-block; margin-right: 20px;">
        <img src="/logos/ZAS_Marke-Kurz_4c.png" alt="https://www.leibniz-zas.de/en/" style="height: 70px; width: auto;"/>
    </a>
    <a href="https://www.leibniz-gemeinschaft.de/en/" target="_blank" rel="noopener noreferrer" style="display: inline-block;">
        <img src="/logos/Leibniz-Gemeinschaft-Logo-ENG_blau.png" alt="https://www.leibniz-gemeinschaft.de/en/" style="height: 60px; width: auto;"/>
    </a>
  </div>

website:
  title: "Reproducible Analyses in R (ZAS Workshop)"
  twitter-card: true
  navbar:
    right:
      - icon: home
        href: https://daniela-palleschi.github.io/
        text: D. Palleschi
      - icon: github
        href: https://github.com/daniela-palleschi/zas-reproducibility-2024
        aria-label: Source Code
      - icon: life-preserver
        href: https://osf.io/vtk2q/
        aria-label: OSF materials
  sidebar:
    style: "docked"
    collapse-level: 1
    search: true
    contents:
    - index.qmd
    - section: "Day 1"
      contents:
        - pages/reproducibility.qmd
        # - pages/R-workflow.qmd
        - pages/rprojects.qmd
    - section: "Day 2"
      contents:
      - pages/literate_programming.qmd
      # - pages/pkg_management.qmd

csl: apa.csl

crossref:
  exm-prefix: ex.   # (default is "Figure")

format:
  html:
    theme:
      light: 
        - flatly
        - custom.scss
      dark:
        - darkly
        - custom.scss
    code-tools: true
    toc: true
    page-layout: full
    embed-resources: false
  revealjs:
    logo: logos/ZAS_Marke-Lang_weiss.svg
    theme: [simple, zas-footer.scss]
    link-external-newwindow: true
    sc-sb-title: true
    code-overflow: wrap
    width: 1600
    height: 900
    progress: true
    scrollable: true
    slide-number: c/t
    code-link: true
    incremental: true
    toc: false
    toc-depth: 2
    toc-title: 'Overview'
    navigation-mode: linear
    controls-layout: bottom-right
    fig-cap-location: top
    font-size: 0.6em
    slide-level: 4
    embed-resources: false
    fig-align: center
    fig-dpi: 300
    simplemenu:
        barhtml:
            header: "<div class='menubar'></a><ul class='menu'></ul><div class='slide-number'></div><div>"
        scale: 0.5
revealjs-plugins:
  - simplemenu # https://github.com/Martinomagnifico/quarto-simplemenu
execute:
  eval: true
  echo: true
  message: false
  error: false
  warning: false
  fig-align: "center"
  fig-asp: .618



